//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WytSky.Mobile.Maui.Skoola.AppResources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WytSky.Mobile.Maui.Skoola.AppResources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Text_AboutUs {
            get {
                return ResourceManager.GetString("Text_AboutUs", resourceCulture);
            }
        }
        
        public static string Text_Close {
            get {
                return ResourceManager.GetString("Text_Close", resourceCulture);
            }
        }
        
        public static string Text_ContactUs {
            get {
                return ResourceManager.GetString("Text_ContactUs", resourceCulture);
            }
        }
        
        public static string Text_Home {
            get {
                return ResourceManager.GetString("Text_Home", resourceCulture);
            }
        }
        
        public static string Text_Language {
            get {
                return ResourceManager.GetString("Text_Language", resourceCulture);
            }
        }
        
        public static string Text_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Text_PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string Text_ShareApp {
            get {
                return ResourceManager.GetString("Text_ShareApp", resourceCulture);
            }
        }
        
        public static string Text_Skip {
            get {
                return ResourceManager.GetString("Text_Skip", resourceCulture);
            }
        }
        
        public static string Text_TermsConditions {
            get {
                return ResourceManager.GetString("Text_TermsConditions", resourceCulture);
            }
        }
        
        public static string Text_DontShow {
            get {
                return ResourceManager.GetString("Text_DontShow", resourceCulture);
            }
        }
        
        public static string Text_Next {
            get {
                return ResourceManager.GetString("Text_Next", resourceCulture);
            }
        }
        
        public static string Text_Previous {
            get {
                return ResourceManager.GetString("Text_Previous", resourceCulture);
            }
        }
        
        public static string Image_BackW_01 {
            get {
                return ResourceManager.GetString("Image_BackW_01", resourceCulture);
            }
        }
        
        public static string Image_Back_01 {
            get {
                return ResourceManager.GetString("Image_Back_01", resourceCulture);
            }
        }
        
        public static string Text_AttachFile {
            get {
                return ResourceManager.GetString("Text_AttachFile", resourceCulture);
            }
        }
        
        public static string Text_Description {
            get {
                return ResourceManager.GetString("Text_Description", resourceCulture);
            }
        }
        
        public static string Text_Email {
            get {
                return ResourceManager.GetString("Text_Email", resourceCulture);
            }
        }
        
        public static string Text_FullName {
            get {
                return ResourceManager.GetString("Text_FullName", resourceCulture);
            }
        }
        
        public static string Text_Phone {
            get {
                return ResourceManager.GetString("Text_Phone", resourceCulture);
            }
        }
        
        public static string Text_SendTicket {
            get {
                return ResourceManager.GetString("Text_SendTicket", resourceCulture);
            }
        }
        
        public static string Text_Subject {
            get {
                return ResourceManager.GetString("Text_Subject", resourceCulture);
            }
        }
        
        public static string Text_Privacy {
            get {
                return ResourceManager.GetString("Text_Privacy", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string Msg_ConnectionError {
            get {
                return ResourceManager.GetString("Msg_ConnectionError", resourceCulture);
            }
        }
        
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        public static string Msg_NoData {
            get {
                return ResourceManager.GetString("Msg_NoData", resourceCulture);
            }
        }
        
        public static string Msg_NoInternetConnection {
            get {
                return ResourceManager.GetString("Msg_NoInternetConnection", resourceCulture);
            }
        }
        
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        public static string Msg_NoValidDescription {
            get {
                return ResourceManager.GetString("Msg_NoValidDescription", resourceCulture);
            }
        }
        
        public static string Msg_NoValidName {
            get {
                return ResourceManager.GetString("Msg_NoValidName", resourceCulture);
            }
        }
        
        public static string Text_AddNew {
            get {
                return ResourceManager.GetString("Text_AddNew", resourceCulture);
            }
        }
        
        public static string Text_Canceled {
            get {
                return ResourceManager.GetString("Text_Canceled", resourceCulture);
            }
        }
        
        public static string Text_Date {
            get {
                return ResourceManager.GetString("Text_Date", resourceCulture);
            }
        }
        
        public static string Text_Done {
            get {
                return ResourceManager.GetString("Text_Done", resourceCulture);
            }
        }
        
        public static string Text_High {
            get {
                return ResourceManager.GetString("Text_High", resourceCulture);
            }
        }
        
        public static string Text_Implementation {
            get {
                return ResourceManager.GetString("Text_Implementation", resourceCulture);
            }
        }
        
        public static string Text_Low {
            get {
                return ResourceManager.GetString("Text_Low", resourceCulture);
            }
        }
        
        public static string Text_Medium {
            get {
                return ResourceManager.GetString("Text_Medium", resourceCulture);
            }
        }
        
        public static string Text_Name {
            get {
                return ResourceManager.GetString("Text_Name", resourceCulture);
            }
        }
        
        public static string Text_Planing {
            get {
                return ResourceManager.GetString("Text_Planing", resourceCulture);
            }
        }
        
        public static string Text_Priority {
            get {
                return ResourceManager.GetString("Text_Priority", resourceCulture);
            }
        }
        
        public static string Text_Save {
            get {
                return ResourceManager.GetString("Text_Save", resourceCulture);
            }
        }
        
        public static string Text_Status {
            get {
                return ResourceManager.GetString("Text_Status", resourceCulture);
            }
        }
        
        public static string Text_ToDoList {
            get {
                return ResourceManager.GetString("Text_ToDoList", resourceCulture);
            }
        }
        
        public static string Text_Back {
            get {
                return ResourceManager.GetString("Text_Back", resourceCulture);
            }
        }
        
        public static string Text_TryAgain {
            get {
                return ResourceManager.GetString("Text_TryAgain", resourceCulture);
            }
        }
        
        public static string Test_OrganiztionCode {
            get {
                return ResourceManager.GetString("Test_OrganiztionCode", resourceCulture);
            }
        }
        
        public static string Text_GetUrl {
            get {
                return ResourceManager.GetString("Text_GetUrl", resourceCulture);
            }
        }
        
        public static string Msg_NotValidOrgCode {
            get {
                return ResourceManager.GetString("Msg_NotValidOrgCode", resourceCulture);
            }
        }
        
        public static string Msg_NotValidPassword {
            get {
                return ResourceManager.GetString("Msg_NotValidPassword", resourceCulture);
            }
        }
        
        public static string Msg_NotValidUserName {
            get {
                return ResourceManager.GetString("Msg_NotValidUserName", resourceCulture);
            }
        }
        
        public static string Msg_NotValidMessage {
            get {
                return ResourceManager.GetString("Msg_NotValidMessage", resourceCulture);
            }
        }
        
        public static string Msg_SendNewMessage {
            get {
                return ResourceManager.GetString("Msg_SendNewMessage", resourceCulture);
            }
        }
        
        public static string Msg_AlreadyHaveAcoount {
            get {
                return ResourceManager.GetString("Msg_AlreadyHaveAcoount", resourceCulture);
            }
        }
        
        public static string Msg_DontHaveAcoount {
            get {
                return ResourceManager.GetString("Msg_DontHaveAcoount", resourceCulture);
            }
        }
        
        public static string Text_Login {
            get {
                return ResourceManager.GetString("Text_Login", resourceCulture);
            }
        }
        
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        public static string Text_Register {
            get {
                return ResourceManager.GetString("Text_Register", resourceCulture);
            }
        }
        
        public static string Text_ResetPassword {
            get {
                return ResourceManager.GetString("Text_ResetPassword", resourceCulture);
            }
        }
        
        public static string Text_SignIn {
            get {
                return ResourceManager.GetString("Text_SignIn", resourceCulture);
            }
        }
        
        public static string Text_SignUp {
            get {
                return ResourceManager.GetString("Text_SignUp", resourceCulture);
            }
        }
        
        public static string Text_WelcomeTo {
            get {
                return ResourceManager.GetString("Text_WelcomeTo", resourceCulture);
            }
        }
        
        public static string Text_Categories {
            get {
                return ResourceManager.GetString("Text_Categories", resourceCulture);
            }
        }
        
        public static string Text_SeeAll {
            get {
                return ResourceManager.GetString("Text_SeeAll", resourceCulture);
            }
        }
        
        public static string Text_BestSell {
            get {
                return ResourceManager.GetString("Text_BestSell", resourceCulture);
            }
        }
        
        public static string Text_Featured {
            get {
                return ResourceManager.GetString("Text_Featured", resourceCulture);
            }
        }
        
        public static string Text_ItemDetails {
            get {
                return ResourceManager.GetString("Text_ItemDetails", resourceCulture);
            }
        }
        
        public static string Text_Reviews {
            get {
                return ResourceManager.GetString("Text_Reviews", resourceCulture);
            }
        }
        
        public static string Text_AddToCart {
            get {
                return ResourceManager.GetString("Text_AddToCart", resourceCulture);
            }
        }
        
        public static string Text_Cart {
            get {
                return ResourceManager.GetString("Text_Cart", resourceCulture);
            }
        }
        
        public static string Text_Continue {
            get {
                return ResourceManager.GetString("Text_Continue", resourceCulture);
            }
        }
        
        public static string Text_Favorites {
            get {
                return ResourceManager.GetString("Text_Favorites", resourceCulture);
            }
        }
        
        public static string Text_MyOrders {
            get {
                return ResourceManager.GetString("Text_MyOrders", resourceCulture);
            }
        }
        
        public static string Text_OrderAgain {
            get {
                return ResourceManager.GetString("Text_OrderAgain", resourceCulture);
            }
        }
        
        public static string Text_Profile {
            get {
                return ResourceManager.GetString("Text_Profile", resourceCulture);
            }
        }
        
        public static string Text_LogOut {
            get {
                return ResourceManager.GetString("Text_LogOut", resourceCulture);
            }
        }
        
        public static string Text_RateApp {
            get {
                return ResourceManager.GetString("Text_RateApp", resourceCulture);
            }
        }
        
        public static string Text_EmailOrPhone {
            get {
                return ResourceManager.GetString("Text_EmailOrPhone", resourceCulture);
            }
        }
        
        public static string Text_FacebookLogin {
            get {
                return ResourceManager.GetString("Text_FacebookLogin", resourceCulture);
            }
        }
        
        public static string Text_Notification {
            get {
                return ResourceManager.GetString("Text_Notification", resourceCulture);
            }
        }
        
        public static string Text_ServiceRequest {
            get {
                return ResourceManager.GetString("Text_ServiceRequest", resourceCulture);
            }
        }
        
        public static string Text_SelectLocation {
            get {
                return ResourceManager.GetString("Text_SelectLocation", resourceCulture);
            }
        }
        
        public static string Text_Location {
            get {
                return ResourceManager.GetString("Text_Location", resourceCulture);
            }
        }
        
        public static string Text_All {
            get {
                return ResourceManager.GetString("Text_All", resourceCulture);
            }
        }
        
        public static string Text_Service {
            get {
                return ResourceManager.GetString("Text_Service", resourceCulture);
            }
        }
        
        public static string Text_ServicAappropriate {
            get {
                return ResourceManager.GetString("Text_ServicAappropriate", resourceCulture);
            }
        }
        
        public static string Text_Loading {
            get {
                return ResourceManager.GetString("Text_Loading", resourceCulture);
            }
        }
        
        public static string Msg_CloseApp {
            get {
                return ResourceManager.GetString("Msg_CloseApp", resourceCulture);
            }
        }
        
        public static string Text_Cancle {
            get {
                return ResourceManager.GetString("Text_Cancle", resourceCulture);
            }
        }
        
        public static string Text_CloseApp {
            get {
                return ResourceManager.GetString("Text_CloseApp", resourceCulture);
            }
        }
        
        public static string Text_AddressDetail {
            get {
                return ResourceManager.GetString("Text_AddressDetail", resourceCulture);
            }
        }
        
        public static string Text_ServiceDetails {
            get {
                return ResourceManager.GetString("Text_ServiceDetails", resourceCulture);
            }
        }
        
        public static string Text_Camera {
            get {
                return ResourceManager.GetString("Text_Camera", resourceCulture);
            }
        }
        
        public static string Text_Gallery {
            get {
                return ResourceManager.GetString("Text_Gallery", resourceCulture);
            }
        }
        
        public static string Text_SelectPhoto {
            get {
                return ResourceManager.GetString("Text_SelectPhoto", resourceCulture);
            }
        }
        
        public static string Text_SelectPhotoFrom {
            get {
                return ResourceManager.GetString("Text_SelectPhotoFrom", resourceCulture);
            }
        }
        
        public static string Text_CameraVideo {
            get {
                return ResourceManager.GetString("Text_CameraVideo", resourceCulture);
            }
        }
        
        public static string Text_Change {
            get {
                return ResourceManager.GetString("Text_Change", resourceCulture);
            }
        }
        
        public static string Text_SelectVideo {
            get {
                return ResourceManager.GetString("Text_SelectVideo", resourceCulture);
            }
        }
        
        public static string Text_SelectVideoFrom {
            get {
                return ResourceManager.GetString("Text_SelectVideoFrom", resourceCulture);
            }
        }
        
        public static string Text_ConfirmPassword {
            get {
                return ResourceManager.GetString("Text_ConfirmPassword", resourceCulture);
            }
        }
        
        public static string Msg_PasswordValdation {
            get {
                return ResourceManager.GetString("Msg_PasswordValdation", resourceCulture);
            }
        }
        
        public static string Msg_NotValidEmail {
            get {
                return ResourceManager.GetString("Msg_NotValidEmail", resourceCulture);
            }
        }
        
        public static string Msg_NotValidName {
            get {
                return ResourceManager.GetString("Msg_NotValidName", resourceCulture);
            }
        }
        
        public static string Msg_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Msg_PasswordNotMatch", resourceCulture);
            }
        }
        
        public static string Msg_NotValidPhone {
            get {
                return ResourceManager.GetString("Msg_NotValidPhone", resourceCulture);
            }
        }
        
        public static string Text_OrderNow {
            get {
                return ResourceManager.GetString("Text_OrderNow", resourceCulture);
            }
        }
        
        public static string Text_AttachPicture {
            get {
                return ResourceManager.GetString("Text_AttachPicture", resourceCulture);
            }
        }
        
        public static string Text_AttachVideo {
            get {
                return ResourceManager.GetString("Text_AttachVideo", resourceCulture);
            }
        }
        
        public static string Text_AttachVoice {
            get {
                return ResourceManager.GetString("Text_AttachVoice", resourceCulture);
            }
        }
        
        public static string Text_Choose {
            get {
                return ResourceManager.GetString("Text_Choose", resourceCulture);
            }
        }
        
        public static string Text_ChooseService {
            get {
                return ResourceManager.GetString("Text_ChooseService", resourceCulture);
            }
        }
        
        public static string Text_GetLocation {
            get {
                return ResourceManager.GetString("Text_GetLocation", resourceCulture);
            }
        }
        
        public static string Text_OrderDetails {
            get {
                return ResourceManager.GetString("Text_OrderDetails", resourceCulture);
            }
        }
        
        public static string Text_Play {
            get {
                return ResourceManager.GetString("Text_Play", resourceCulture);
            }
        }
        
        public static string Text_Record {
            get {
                return ResourceManager.GetString("Text_Record", resourceCulture);
            }
        }
        
        public static string Text_StopRecording {
            get {
                return ResourceManager.GetString("Text_StopRecording", resourceCulture);
            }
        }
        
        public static string Text_Order {
            get {
                return ResourceManager.GetString("Text_Order", resourceCulture);
            }
        }
        
        public static string Text_Address {
            get {
                return ResourceManager.GetString("Text_Address", resourceCulture);
            }
        }
        
        public static string Text_Approval {
            get {
                return ResourceManager.GetString("Text_Approval", resourceCulture);
            }
        }
        
        public static string Text_AwaitingApproval {
            get {
                return ResourceManager.GetString("Text_AwaitingApproval", resourceCulture);
            }
        }
        
        public static string Text_Technical {
            get {
                return ResourceManager.GetString("Text_Technical", resourceCulture);
            }
        }
        
        public static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        public static string Msg_NotAvailabelService {
            get {
                return ResourceManager.GetString("Msg_NotAvailabelService", resourceCulture);
            }
        }
        
        public static string Text_Yes {
            get {
                return ResourceManager.GetString("Text_Yes", resourceCulture);
            }
        }
        
        public static string Text_From {
            get {
                return ResourceManager.GetString("Text_From", resourceCulture);
            }
        }
        
        public static string Text_To {
            get {
                return ResourceManager.GetString("Text_To", resourceCulture);
            }
        }
        
        public static string Text_Details {
            get {
                return ResourceManager.GetString("Text_Details", resourceCulture);
            }
        }
        
        public static string Text_Notes {
            get {
                return ResourceManager.GetString("Text_Notes", resourceCulture);
            }
        }
        
        public static string Text_PersonalData {
            get {
                return ResourceManager.GetString("Text_PersonalData", resourceCulture);
            }
        }
        
        public static string Msg_TimeExpired {
            get {
                return ResourceManager.GetString("Msg_TimeExpired", resourceCulture);
            }
        }
        
        public static string Msg_UserNoValid {
            get {
                return ResourceManager.GetString("Msg_UserNoValid", resourceCulture);
            }
        }
        
        public static string Text_Preview {
            get {
                return ResourceManager.GetString("Text_Preview", resourceCulture);
            }
        }
        
        public static string Msg_NotValidNewPassword {
            get {
                return ResourceManager.GetString("Msg_NotValidNewPassword", resourceCulture);
            }
        }
        
        public static string Text_ChangePassword {
            get {
                return ResourceManager.GetString("Text_ChangePassword", resourceCulture);
            }
        }
        
        public static string Text_NewPassword {
            get {
                return ResourceManager.GetString("Text_NewPassword", resourceCulture);
            }
        }
        
        public static string Text_OldPassword {
            get {
                return ResourceManager.GetString("Text_OldPassword", resourceCulture);
            }
        }
        
        public static string Text_AppleLogin {
            get {
                return ResourceManager.GetString("Text_AppleLogin", resourceCulture);
            }
        }
        
        public static string Text_BrowseServices {
            get {
                return ResourceManager.GetString("Text_BrowseServices", resourceCulture);
            }
        }
        
        public static string Msg_UnableGetLocation {
            get {
                return ResourceManager.GetString("Msg_UnableGetLocation", resourceCulture);
            }
        }
        
        public static string Text_OrderNumber {
            get {
                return ResourceManager.GetString("Text_OrderNumber", resourceCulture);
            }
        }
        
        public static string Msg_EmailNotValid {
            get {
                return ResourceManager.GetString("Msg_EmailNotValid", resourceCulture);
            }
        }
        
        public static string Msg_SocialEmail {
            get {
                return ResourceManager.GetString("Msg_SocialEmail", resourceCulture);
            }
        }
        
        public static string Msg_VerficationCode {
            get {
                return ResourceManager.GetString("Msg_VerficationCode", resourceCulture);
            }
        }
        
        public static string Text_VerficationCode {
            get {
                return ResourceManager.GetString("Text_VerficationCode", resourceCulture);
            }
        }
        
        public static string Text_CancelOrder {
            get {
                return ResourceManager.GetString("Text_CancelOrder", resourceCulture);
            }
        }
        
        public static string Text_Completed {
            get {
                return ResourceManager.GetString("Text_Completed", resourceCulture);
            }
        }
        
        public static string Text_MsgContact {
            get {
                return ResourceManager.GetString("Text_MsgContact", resourceCulture);
            }
        }
        
        public static string Text_BrowseProducts {
            get {
                return ResourceManager.GetString("Text_BrowseProducts", resourceCulture);
            }
        }
        
        public static string Msg_EmailAlreadyUse {
            get {
                return ResourceManager.GetString("Msg_EmailAlreadyUse", resourceCulture);
            }
        }
        
        public static string Text_CheckOut {
            get {
                return ResourceManager.GetString("Text_CheckOut", resourceCulture);
            }
        }
        
        public static string Text_SelectItems {
            get {
                return ResourceManager.GetString("Text_SelectItems", resourceCulture);
            }
        }
        
        public static string Text_Total {
            get {
                return ResourceManager.GetString("Text_Total", resourceCulture);
            }
        }
        
        public static string Text_InProcess {
            get {
                return ResourceManager.GetString("Text_InProcess", resourceCulture);
            }
        }
        
        public static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        public static string Text_Message {
            get {
                return ResourceManager.GetString("Text_Message", resourceCulture);
            }
        }
        
        public static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
        
        public static string Text_Warning {
            get {
                return ResourceManager.GetString("Text_Warning", resourceCulture);
            }
        }
        
        public static string Text_Trending {
            get {
                return ResourceManager.GetString("Text_Trending", resourceCulture);
            }
        }
        
        public static string Text_ContinueAsGuest {
            get {
                return ResourceManager.GetString("Text_ContinueAsGuest", resourceCulture);
            }
        }
        
        public static string Text_EnterYourEmail {
            get {
                return ResourceManager.GetString("Text_EnterYourEmail", resourceCulture);
            }
        }
        
        public static string Text_EnterYourName {
            get {
                return ResourceManager.GetString("Text_EnterYourName", resourceCulture);
            }
        }
        
        public static string Text_EnterYourPassword {
            get {
                return ResourceManager.GetString("Text_EnterYourPassword", resourceCulture);
            }
        }
        
        public static string Text_EnterYourPhone {
            get {
                return ResourceManager.GetString("Text_EnterYourPhone", resourceCulture);
            }
        }
        
        public static string Text_ForgotYourPassword {
            get {
                return ResourceManager.GetString("Text_ForgotYourPassword", resourceCulture);
            }
        }
        
        public static string Text_ForgotYourUsername {
            get {
                return ResourceManager.GetString("Text_ForgotYourUsername", resourceCulture);
            }
        }
        
        public static string Text_ReEnterYourPassword {
            get {
                return ResourceManager.GetString("Text_ReEnterYourPassword", resourceCulture);
            }
        }
        
        public static string Text_Search {
            get {
                return ResourceManager.GetString("Text_Search", resourceCulture);
            }
        }
        
        public static string Text_Add {
            get {
                return ResourceManager.GetString("Text_Add", resourceCulture);
            }
        }
        
        public static string Msg_NoDataFound {
            get {
                return ResourceManager.GetString("Msg_NoDataFound", resourceCulture);
            }
        }
        
        public static string Msg_SessionExpired {
            get {
                return ResourceManager.GetString("Msg_SessionExpired", resourceCulture);
            }
        }
        
        public static string Text_DeliveryAddress {
            get {
                return ResourceManager.GetString("Text_DeliveryAddress", resourceCulture);
            }
        }
        
        public static string Text_HelpsFaqs {
            get {
                return ResourceManager.GetString("Text_HelpsFaqs", resourceCulture);
            }
        }
        
        public static string Text_MyProfile {
            get {
                return ResourceManager.GetString("Text_MyProfile", resourceCulture);
            }
        }
        
        public static string Text_PaymentMethods {
            get {
                return ResourceManager.GetString("Text_PaymentMethods", resourceCulture);
            }
        }
        
        public static string Text_Settings {
            get {
                return ResourceManager.GetString("Text_Settings", resourceCulture);
            }
        }
        
        public static string Text_Voucher {
            get {
                return ResourceManager.GetString("Text_Voucher", resourceCulture);
            }
        }
        
        public static string Text_CreateAccount {
            get {
                return ResourceManager.GetString("Text_CreateAccount", resourceCulture);
            }
        }
        
        public static string Text_EmailMeAboutSpecialPricing {
            get {
                return ResourceManager.GetString("Text_EmailMeAboutSpecialPricing", resourceCulture);
            }
        }
        
        public static string Text_Facebook {
            get {
                return ResourceManager.GetString("Text_Facebook", resourceCulture);
            }
        }
        
        public static string Text_Google {
            get {
                return ResourceManager.GetString("Text_Google", resourceCulture);
            }
        }
        
        public static string Text_keepMeSignIn {
            get {
                return ResourceManager.GetString("Text_keepMeSignIn", resourceCulture);
            }
        }
        
        public static string Text_LoginToYourAccount {
            get {
                return ResourceManager.GetString("Text_LoginToYourAccount", resourceCulture);
            }
        }
        
        public static string Text_OrContinueWith {
            get {
                return ResourceManager.GetString("Text_OrContinueWith", resourceCulture);
            }
        }
        
        public static string Text_SignUpForFree {
            get {
                return ResourceManager.GetString("Text_SignUpForFree", resourceCulture);
            }
        }
        
        public static string Text_AddBonusToDelivery {
            get {
                return ResourceManager.GetString("Text_AddBonusToDelivery", resourceCulture);
            }
        }
        
        public static string Text_AddPaymentMethod {
            get {
                return ResourceManager.GetString("Text_AddPaymentMethod", resourceCulture);
            }
        }
        
        public static string Text_Apply {
            get {
                return ResourceManager.GetString("Text_Apply", resourceCulture);
            }
        }
        
        public static string Text_BonusToDelivery {
            get {
                return ResourceManager.GetString("Text_BonusToDelivery", resourceCulture);
            }
        }
        
        public static string Text_CashOnDelivery {
            get {
                return ResourceManager.GetString("Text_CashOnDelivery", resourceCulture);
            }
        }
        
        public static string Text_CreditCard {
            get {
                return ResourceManager.GetString("Text_CreditCard", resourceCulture);
            }
        }
        
        public static string Text_DeliverTo {
            get {
                return ResourceManager.GetString("Text_DeliverTo", resourceCulture);
            }
        }
        
        public static string Text_Delivery {
            get {
                return ResourceManager.GetString("Text_Delivery", resourceCulture);
            }
        }
        
        public static string Text_DeliveryFromRestaurantName {
            get {
                return ResourceManager.GetString("Text_DeliveryFromRestaurantName", resourceCulture);
            }
        }
        
        public static string Text_Discount50 {
            get {
                return ResourceManager.GetString("Text_Discount50", resourceCulture);
            }
        }
        
        public static string Text_FeaturedRestaurant {
            get {
                return ResourceManager.GetString("Text_FeaturedRestaurant", resourceCulture);
            }
        }
        
        public static string Text_FreeDelivery {
            get {
                return ResourceManager.GetString("Text_FreeDelivery", resourceCulture);
            }
        }
        
        public static string Text_FreeDeliveryForOrder {
            get {
                return ResourceManager.GetString("Text_FreeDeliveryForOrder", resourceCulture);
            }
        }
        
        public static string Text_FreeDeliveryOneMonth {
            get {
                return ResourceManager.GetString("Text_FreeDeliveryOneMonth", resourceCulture);
            }
        }
        
        public static string Text_Items {
            get {
                return ResourceManager.GetString("Text_Items", resourceCulture);
            }
        }
        
        public static string Text_MostPopular {
            get {
                return ResourceManager.GetString("Text_MostPopular", resourceCulture);
            }
        }
        
        public static string Text_NearestRestaurant {
            get {
                return ResourceManager.GetString("Text_NearestRestaurant", resourceCulture);
            }
        }
        
        public static string Text_PlaceOrder {
            get {
                return ResourceManager.GetString("Text_PlaceOrder", resourceCulture);
            }
        }
        
        public static string Text_PromoCode {
            get {
                return ResourceManager.GetString("Text_PromoCode", resourceCulture);
            }
        }
        
        public static string Text_Ratings {
            get {
                return ResourceManager.GetString("Text_Ratings", resourceCulture);
            }
        }
        
        public static string Text_RestaurantsOffers {
            get {
                return ResourceManager.GetString("Text_RestaurantsOffers", resourceCulture);
            }
        }
        
        public static string Text_Subtotal {
            get {
                return ResourceManager.GetString("Text_Subtotal", resourceCulture);
            }
        }
        
        public static string Text_Time {
            get {
                return ResourceManager.GetString("Text_Time", resourceCulture);
            }
        }
        
        public static string Text_TotalPayment {
            get {
                return ResourceManager.GetString("Text_TotalPayment", resourceCulture);
            }
        }
        
        public static string Text_Vat {
            get {
                return ResourceManager.GetString("Text_Vat", resourceCulture);
            }
        }
        
        public static string Text_ViewMore {
            get {
                return ResourceManager.GetString("Text_ViewMore", resourceCulture);
            }
        }
        
        public static string Text_VodafoneCash {
            get {
                return ResourceManager.GetString("Text_VodafoneCash", resourceCulture);
            }
        }
        
        public static string Text_Alert {
            get {
                return ResourceManager.GetString("Text_Alert", resourceCulture);
            }
        }
        
        public static string Text_CartItemsDeleted {
            get {
                return ResourceManager.GetString("Text_CartItemsDeleted", resourceCulture);
            }
        }
        
        public static string Text_CodeSentTo {
            get {
                return ResourceManager.GetString("Text_CodeSentTo", resourceCulture);
            }
        }
        
        public static string Text_CodeWillExpireIn {
            get {
                return ResourceManager.GetString("Text_CodeWillExpireIn", resourceCulture);
            }
        }
        
        public static string Text_Congrats {
            get {
                return ResourceManager.GetString("Text_Congrats", resourceCulture);
            }
        }
        
        public static string Text_Enter4DigitVerificationCode {
            get {
                return ResourceManager.GetString("Text_Enter4DigitVerificationCode", resourceCulture);
            }
        }
        
        public static string Text_FindFoodRestaurant {
            get {
                return ResourceManager.GetString("Text_FindFoodRestaurant", resourceCulture);
            }
        }
        
        public static string Text_No {
            get {
                return ResourceManager.GetString("Text_No", resourceCulture);
            }
        }
        
        public static string Text_PasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("Text_PasswordResetSuccessfully", resourceCulture);
            }
        }
        
        public static string Text_ProfileReadyForUse {
            get {
                return ResourceManager.GetString("Text_ProfileReadyForUse", resourceCulture);
            }
        }
        
        public static string Text_SelectWhichContact {
            get {
                return ResourceManager.GetString("Text_SelectWhichContact", resourceCulture);
            }
        }
        
        public static string Text_SetLocation {
            get {
                return ResourceManager.GetString("Text_SetLocation", resourceCulture);
            }
        }
        
        public static string Text_ThisDataWillDisplayedInYourProfile {
            get {
                return ResourceManager.GetString("Text_ThisDataWillDisplayedInYourProfile", resourceCulture);
            }
        }
        
        public static string Text_UploadYourPhotoProfile {
            get {
                return ResourceManager.GetString("Text_UploadYourPhotoProfile", resourceCulture);
            }
        }
        
        public static string Text_ViaEmail {
            get {
                return ResourceManager.GetString("Text_ViaEmail", resourceCulture);
            }
        }
        
        public static string Text_ViaSms {
            get {
                return ResourceManager.GetString("Text_ViaSms", resourceCulture);
            }
        }
        
        public static string Text_YouHaveCartItems {
            get {
                return ResourceManager.GetString("Text_YouHaveCartItems", resourceCulture);
            }
        }
        
        public static string Text_YourLocation {
            get {
                return ResourceManager.GetString("Text_YourLocation", resourceCulture);
            }
        }
        
        public static string Text_CartItemsSavedLocally {
            get {
                return ResourceManager.GetString("Text_CartItemsSavedLocally", resourceCulture);
            }
        }
        
        public static string Text_MustLogin {
            get {
                return ResourceManager.GetString("Text_MustLogin", resourceCulture);
            }
        }
        
        public static string Text_Nearest {
            get {
                return ResourceManager.GetString("Text_Nearest", resourceCulture);
            }
        }
        
        public static string Text_Offers {
            get {
                return ResourceManager.GetString("Text_Offers", resourceCulture);
            }
        }
        
        public static string Text_ThereAreItemsInCart {
            get {
                return ResourceManager.GetString("Text_ThereAreItemsInCart", resourceCulture);
            }
        }
        
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        public static string Text_History {
            get {
                return ResourceManager.GetString("Text_History", resourceCulture);
            }
        }
        
        public static string Text_RateOrder {
            get {
                return ResourceManager.GetString("Text_RateOrder", resourceCulture);
            }
        }
        
        public static string Text_ReOrder {
            get {
                return ResourceManager.GetString("Text_ReOrder", resourceCulture);
            }
        }
        
        public static string Text_TrackOrder {
            get {
                return ResourceManager.GetString("Text_TrackOrder", resourceCulture);
            }
        }
        
        public static string Text_UpComing {
            get {
                return ResourceManager.GetString("Text_UpComing", resourceCulture);
            }
        }
        
        public static string Text_Delivered {
            get {
                return ResourceManager.GetString("Text_Delivered", resourceCulture);
            }
        }
        
        public static string Text_DeliveredBy {
            get {
                return ResourceManager.GetString("Text_DeliveredBy", resourceCulture);
            }
        }
        
        public static string Text_Delivering {
            get {
                return ResourceManager.GetString("Text_Delivering", resourceCulture);
            }
        }
        
        public static string Text_EstimatedTime {
            get {
                return ResourceManager.GetString("Text_EstimatedTime", resourceCulture);
            }
        }
        
        public static string Text_InPrepparation {
            get {
                return ResourceManager.GetString("Text_InPrepparation", resourceCulture);
            }
        }
        
        public static string Text_PaymentMethod {
            get {
                return ResourceManager.GetString("Text_PaymentMethod", resourceCulture);
            }
        }
        
        public static string Text_Send {
            get {
                return ResourceManager.GetString("Text_Send", resourceCulture);
            }
        }
        
        public static string Text_FirstName {
            get {
                return ResourceManager.GetString("Text_FirstName", resourceCulture);
            }
        }
        
        public static string Text_LastName {
            get {
                return ResourceManager.GetString("Text_LastName", resourceCulture);
            }
        }
        
        public static string Text_Or {
            get {
                return ResourceManager.GetString("Text_Or", resourceCulture);
            }
        }
        
        public static string Text_OrSignUpWith {
            get {
                return ResourceManager.GetString("Text_OrSignUpWith", resourceCulture);
            }
        }
        
        public static string Text_RememberMe {
            get {
                return ResourceManager.GetString("Text_RememberMe", resourceCulture);
            }
        }
        
        public static string Text_SignInWithApple {
            get {
                return ResourceManager.GetString("Text_SignInWithApple", resourceCulture);
            }
        }
        
        public static string Text_SignInWithGoogle {
            get {
                return ResourceManager.GetString("Text_SignInWithGoogle", resourceCulture);
            }
        }
        
        public static string Text_AccountVerified {
            get {
                return ResourceManager.GetString("Text_AccountVerified", resourceCulture);
            }
        }
        
        public static string Text_EnrollNow {
            get {
                return ResourceManager.GetString("Text_EnrollNow", resourceCulture);
            }
        }
        
        public static string Text_ForgetPassword {
            get {
                return ResourceManager.GetString("Text_ForgetPassword", resourceCulture);
            }
        }
        
        public static string Text_ForgotPassword {
            get {
                return ResourceManager.GetString("Text_ForgotPassword", resourceCulture);
            }
        }
        
        public static string Text_Hi {
            get {
                return ResourceManager.GetString("Text_Hi", resourceCulture);
            }
        }
        
        public static string Text_HowDidYouHearAboutUs {
            get {
                return ResourceManager.GetString("Text_HowDidYouHearAboutUs", resourceCulture);
            }
        }
        
        public static string Text_MostPopularCourses {
            get {
                return ResourceManager.GetString("Text_MostPopularCourses", resourceCulture);
            }
        }
        
        public static string Text_NotGetTheCode {
            get {
                return ResourceManager.GetString("Text_NotGetTheCode", resourceCulture);
            }
        }
        
        public static string Text_PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("Text_PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        public static string Text_PhoneVerified {
            get {
                return ResourceManager.GetString("Text_PhoneVerified", resourceCulture);
            }
        }
        
        public static string Text_PleaseTypeCode {
            get {
                return ResourceManager.GetString("Text_PleaseTypeCode", resourceCulture);
            }
        }
        
        public static string Text_Resend {
            get {
                return ResourceManager.GetString("Text_Resend", resourceCulture);
            }
        }
        
        public static string Text_TopMentors {
            get {
                return ResourceManager.GetString("Text_TopMentors", resourceCulture);
            }
        }
        
        public static string Text_TopRatedCourses {
            get {
                return ResourceManager.GetString("Text_TopRatedCourses", resourceCulture);
            }
        }
        
        public static string Text_ViewAll {
            get {
                return ResourceManager.GetString("Text_ViewAll", resourceCulture);
            }
        }
        
        public static string Text_WelcomeToQurani {
            get {
                return ResourceManager.GetString("Text_WelcomeToQurani", resourceCulture);
            }
        }
        
        public static string Text_WillSendCode {
            get {
                return ResourceManager.GetString("Text_WillSendCode", resourceCulture);
            }
        }
        
        public static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
        
        public static string Text_AboutCourse {
            get {
                return ResourceManager.GetString("Text_AboutCourse", resourceCulture);
            }
        }
        
        public static string Text_Lessons {
            get {
                return ResourceManager.GetString("Text_Lessons", resourceCulture);
            }
        }
        
        public static string Text_Mentor {
            get {
                return ResourceManager.GetString("Text_Mentor", resourceCulture);
            }
        }
        
        public static string Text_Courses {
            get {
                return ResourceManager.GetString("Text_Courses", resourceCulture);
            }
        }
        
        public static string Text_Students {
            get {
                return ResourceManager.GetString("Text_Students", resourceCulture);
            }
        }
        
        public static string Text_Website {
            get {
                return ResourceManager.GetString("Text_Website", resourceCulture);
            }
        }
        
        public static string Text_Mentors {
            get {
                return ResourceManager.GetString("Text_Mentors", resourceCulture);
            }
        }
        
        public static string Text_MyCourses {
            get {
                return ResourceManager.GetString("Text_MyCourses", resourceCulture);
            }
        }
        
        public static string Text_Certificate {
            get {
                return ResourceManager.GetString("Text_Certificate", resourceCulture);
            }
        }
        
        public static string Text_Ongoing {
            get {
                return ResourceManager.GetString("Text_Ongoing", resourceCulture);
            }
        }
        
        public static string Text_Chat {
            get {
                return ResourceManager.GetString("Text_Chat", resourceCulture);
            }
        }
        
        public static string Text_ClearAll {
            get {
                return ResourceManager.GetString("Text_ClearAll", resourceCulture);
            }
        }
        
        public static string Text_DarkMode {
            get {
                return ResourceManager.GetString("Text_DarkMode", resourceCulture);
            }
        }
        
        public static string Text_HelpCenter {
            get {
                return ResourceManager.GetString("Text_HelpCenter", resourceCulture);
            }
        }
        
        public static string Text_InviteFriends {
            get {
                return ResourceManager.GetString("Text_InviteFriends", resourceCulture);
            }
        }
        
        public static string Text_Payment {
            get {
                return ResourceManager.GetString("Text_Payment", resourceCulture);
            }
        }
        
        public static string Text_Security {
            get {
                return ResourceManager.GetString("Text_Security", resourceCulture);
            }
        }
        
        public static string Text_AppUpdate {
            get {
                return ResourceManager.GetString("Text_AppUpdate", resourceCulture);
            }
        }
        
        public static string Text_Arabic {
            get {
                return ResourceManager.GetString("Text_Arabic", resourceCulture);
            }
        }
        
        public static string Text_BiometricId {
            get {
                return ResourceManager.GetString("Text_BiometricId", resourceCulture);
            }
        }
        
        public static string Text_BirthDate {
            get {
                return ResourceManager.GetString("Text_BirthDate", resourceCulture);
            }
        }
        
        public static string Text_Cashback {
            get {
                return ResourceManager.GetString("Text_Cashback", resourceCulture);
            }
        }
        
        public static string Text_Country {
            get {
                return ResourceManager.GetString("Text_Country", resourceCulture);
            }
        }
        
        public static string Text_CurrentPassword {
            get {
                return ResourceManager.GetString("Text_CurrentPassword", resourceCulture);
            }
        }
        
        public static string Text_EditProfile {
            get {
                return ResourceManager.GetString("Text_EditProfile", resourceCulture);
            }
        }
        
        public static string Text_EnglishUK {
            get {
                return ResourceManager.GetString("Text_EnglishUK", resourceCulture);
            }
        }
        
        public static string Text_EnglishUS {
            get {
                return ResourceManager.GetString("Text_EnglishUS", resourceCulture);
            }
        }
        
        public static string Text_FaceId {
            get {
                return ResourceManager.GetString("Text_FaceId", resourceCulture);
            }
        }
        
        public static string Text_Gender {
            get {
                return ResourceManager.GetString("Text_Gender", resourceCulture);
            }
        }
        
        public static string Text_GeneralNotification {
            get {
                return ResourceManager.GetString("Text_GeneralNotification", resourceCulture);
            }
        }
        
        public static string Text_NewPasswordCreatedSuccessfully {
            get {
                return ResourceManager.GetString("Text_NewPasswordCreatedSuccessfully", resourceCulture);
            }
        }
        
        public static string Text_SaveChanges {
            get {
                return ResourceManager.GetString("Text_SaveChanges", resourceCulture);
            }
        }
        
        public static string Text_Sound {
            get {
                return ResourceManager.GetString("Text_Sound", resourceCulture);
            }
        }
        
        public static string Text_SpecialOffers {
            get {
                return ResourceManager.GetString("Text_SpecialOffers", resourceCulture);
            }
        }
        
        public static string Text_Title {
            get {
                return ResourceManager.GetString("Text_Title", resourceCulture);
            }
        }
        
        public static string Text_Vibrate {
            get {
                return ResourceManager.GetString("Text_Vibrate", resourceCulture);
            }
        }
        
        public static string Text_AddNewCard {
            get {
                return ResourceManager.GetString("Text_AddNewCard", resourceCulture);
            }
        }
        
        public static string Text_CardAddedSuccessfully {
            get {
                return ResourceManager.GetString("Text_CardAddedSuccessfully", resourceCulture);
            }
        }
        
        public static string Text_CardNumber {
            get {
                return ResourceManager.GetString("Text_CardNumber", resourceCulture);
            }
        }
        
        public static string Text_Connected {
            get {
                return ResourceManager.GetString("Text_Connected", resourceCulture);
            }
        }
        
        public static string Text_CVV {
            get {
                return ResourceManager.GetString("Text_CVV", resourceCulture);
            }
        }
        
        public static string Text_Expiration {
            get {
                return ResourceManager.GetString("Text_Expiration", resourceCulture);
            }
        }
        
        public static string Text_HolderName {
            get {
                return ResourceManager.GetString("Text_HolderName", resourceCulture);
            }
        }
        
        public static string Text_NotConnected {
            get {
                return ResourceManager.GetString("Text_NotConnected", resourceCulture);
            }
        }
        
        public static string Text_CustomerService {
            get {
                return ResourceManager.GetString("Text_CustomerService", resourceCulture);
            }
        }
        
        public static string Text_EnrollToCourse {
            get {
                return ResourceManager.GetString("Text_EnrollToCourse", resourceCulture);
            }
        }
        
        public static string Text_Faq {
            get {
                return ResourceManager.GetString("Text_Faq", resourceCulture);
            }
        }
        
        public static string Text_Instgram {
            get {
                return ResourceManager.GetString("Text_Instgram", resourceCulture);
            }
        }
        
        public static string Text_PayNow {
            get {
                return ResourceManager.GetString("Text_PayNow", resourceCulture);
            }
        }
        
        public static string Text_Twitter {
            get {
                return ResourceManager.GetString("Text_Twitter", resourceCulture);
            }
        }
        
        public static string Text_Whatsapp {
            get {
                return ResourceManager.GetString("Text_Whatsapp", resourceCulture);
            }
        }
        
        public static string Text_CostDetails {
            get {
                return ResourceManager.GetString("Text_CostDetails", resourceCulture);
            }
        }
        
        public static string PaymentAddedSuccessfully {
            get {
                return ResourceManager.GetString("PaymentAddedSuccessfully", resourceCulture);
            }
        }
        
        public static string VerifyAccount {
            get {
                return ResourceManager.GetString("VerifyAccount", resourceCulture);
            }
        }
        
        public static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        public static string CanUseYourAccount {
            get {
                return ResourceManager.GetString("CanUseYourAccount", resourceCulture);
            }
        }
        
        public static string Text_Comments {
            get {
                return ResourceManager.GetString("Text_Comments", resourceCulture);
            }
        }
        
        public static string Text_Questions {
            get {
                return ResourceManager.GetString("Text_Questions", resourceCulture);
            }
        }
        
        public static string Text_Attachments {
            get {
                return ResourceManager.GetString("Text_Attachments", resourceCulture);
            }
        }
        
        public static string Text_UserType {
            get {
                return ResourceManager.GetString("Text_UserType", resourceCulture);
            }
        }
        
        public static string Text_Student {
            get {
                return ResourceManager.GetString("Text_Student", resourceCulture);
            }
        }
        
        public static string Text_Parent {
            get {
                return ResourceManager.GetString("Text_Parent", resourceCulture);
            }
        }
        
        public static string Text_Teatcher {
            get {
                return ResourceManager.GetString("Text_Teatcher", resourceCulture);
            }
        }
        
        public static string Text_DemoVideo {
            get {
                return ResourceManager.GetString("Text_DemoVideo", resourceCulture);
            }
        }
        
        public static string Text_ExternalLink {
            get {
                return ResourceManager.GetString("Text_ExternalLink", resourceCulture);
            }
        }
        
        public static string Text_DownloadAttachments {
            get {
                return ResourceManager.GetString("Text_DownloadAttachments", resourceCulture);
            }
        }
        
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        public static string CentersNumber {
            get {
                return ResourceManager.GetString("CentersNumber", resourceCulture);
            }
        }
        
        public static string Text_Region {
            get {
                return ResourceManager.GetString("Text_Region", resourceCulture);
            }
        }
        
        public static string ComplexName {
            get {
                return ResourceManager.GetString("ComplexName", resourceCulture);
            }
        }
        
        public static string CenterNameAr {
            get {
                return ResourceManager.GetString("CenterNameAr", resourceCulture);
            }
        }
        
        public static string CenterNameEn {
            get {
                return ResourceManager.GetString("CenterNameEn", resourceCulture);
            }
        }
        
        public static string DitrictName {
            get {
                return ResourceManager.GetString("DitrictName", resourceCulture);
            }
        }
        
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        public static string Staffs {
            get {
                return ResourceManager.GetString("Staffs", resourceCulture);
            }
        }
        
        public static string StudyGroups {
            get {
                return ResourceManager.GetString("StudyGroups", resourceCulture);
            }
        }
        
        public static string StudyGroupAr {
            get {
                return ResourceManager.GetString("StudyGroupAr", resourceCulture);
            }
        }
        
        public static string StudyGroupEn {
            get {
                return ResourceManager.GetString("StudyGroupEn", resourceCulture);
            }
        }
        
        public static string Complexes {
            get {
                return ResourceManager.GetString("Complexes", resourceCulture);
            }
        }
    }
}
